version: 2
jobs:
    test_krs:
        docker:
            - image: circleci/python:3.8
              environment:
                KEYCLOAK_URL: http://localhost:8080
                LDAP_URL: ldap://localhost:1389
                USERNAME: admin
                PASSWORD: admin
            - image: quay.io/keycloak/keycloak:10.0.2
              environment:
                KEYCLOAK_USER: admin
                KEYCLOAK_PASSWORD: admin
            - image: bitnami/openldap:2
              environment:
                LDAP_PORT_NUMBER: 1389
                LDAP_ADMIN_USERNAME: admin
                LDAP_ADMIN_PASSWORD: admin
                LDAP_ROOT: "dc=icecube,dc=wisc,dc=edu"
                LDAP_CUSTOM_LDIF_DIR: "/ldifs"
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                . env/bin/activate &&
                python -m pytest tests/krs --log-level=INFO
    test_actions:
        docker:
            - image: circleci/python:3.8
              environment:
                KEYCLOAK_URL: http://localhost:8080
                LDAP_URL: ldap://localhost:1389
                USERNAME: admin
                PASSWORD: admin
            - image: quay.io/keycloak/keycloak:10.0.2
              environment:
                KEYCLOAK_USER: admin
                KEYCLOAK_PASSWORD: admin
            - image: bitnami/openldap:2
              environment:
                LDAP_PORT_NUMBER: 1389
                LDAP_ADMIN_USERNAME: admin
                LDAP_ADMIN_PASSWORD: admin
                LDAP_ROOT: "dc=icecube,dc=wisc,dc=edu"
                LDAP_CUSTOM_LDIF_DIR: "/ldifs"
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                . env/bin/activate &&
                python -m pytest tests/actions --log-level=INFO
    test_user_mgmt:
        docker:
            - image: circleci/python:3.8
              environment:
                KEYCLOAK_URL: http://localhost:8080
                USERNAME: admin
                PASSWORD: admin
            - image: circleci/mongo:3.7.9-ram
            - image: quay.io/keycloak/keycloak:10.0.2
              environment:
                KEYCLOAK_USER: admin
                KEYCLOAK_PASSWORD: admin
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                . env/bin/activate &&
                python -m pytest tests/user_mgmt --log-level=INFO
    test_flake8:
        docker:
            - image: circleci/python:3.8
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                . env/bin/activate &&
                flake8
    deploy:
        docker:
            - image: circleci/buildpack-deps:stretch
              environment:
                IMAGE_NAME: wipac/keycloak-rest-services
        steps:
            - checkout
            - setup_remote_docker
            - run: |
                echo 'export TAG="${CIRCLE_TAG:=latest}"' >> $BASH_ENV
            - run: |
                docker build -t $IMAGE_NAME:$TAG .
            - run: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
                docker push $IMAGE_NAME:$TAG
workflows:
    version: 2
    build_and_test:
        jobs:
            - test_krs
            - test_actions
            - test_user_mgmt
            - test_flake8
            - deploy:
                context: docker
                requires:
                    - test_krs
                    - test_actions
                    - test_user_mgmt
                    - test_flake8
                filters:
                    branches:
                        only: master

    release:
        jobs:
            - deploy:
                context: docker
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /^v?\d+\.\d+\.\d+$/
