version: 2
jobs:
    test:
        docker:
            - image: circleci/python:3.8
              environment:
                keycloak_url: http://localhost:8080
                username: admin
                password: admin
            #- image: circleci/mongo:3.7.9-ram
            - image: jboss/keycloak:8.0.2
              environment:
                KEYCLOAK_USER: admin
                KEYCLOAK_PASSWORD: admin
        steps:
            - checkout
            - run: ./setupenv.sh
            - run: |
                . env/bin/activate &&
                pytest
workflows:
    version: 2
    build_and_test:
        jobs:
            - test
