
name: Build docs

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install deps
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs mkdocs-material
    - name: Build docs
      run: |
        mkdocs build
    - name: Tar docs
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        cd site && tar -zcf ../docs.tar.gz *
    - name: Upload html
      if: ${{ github.event_name != 'pull_request' }}
      env:
        USER: ${{ secrets.DOCS_USERNAME }}
        PASS: ${{ secrets.DOCS_PASSWORD }}
      run: |
        curl --data-binary "@docs.tar.gz" -XPUT "https://$USER:$PASS@docs.icecube.aq/api/upload?path=Madison-account/user-workflow"
